ps2smap-objs			:= smap.o
ps2smaprpc-objs			:= smaprpc.o
ps2pad-objs			:= pad.o
ps2cdvd-objs			:= cdvd.o cdvdaltdev.o cdvddev.o cdvdutil.o

obj-$(CONFIG_PS2_ETHER_SMAP)	+= ps2smap.o
obj-$(CONFIG_PS2_ETHER_SMAPRPC)	+= ps2smaprpc.o
obj-$(CONFIG_SONY_PS2)		+= sysproc.o
obj-$(CONFIG_PS2_PAD)		+= ps2pad.o
obj-$(CONFIG_PS2_CDVD)		+= ps2cdvd.o
